# Generated by Django 4.1 on 2022-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0002_alter_divorcement_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcement',
            name='child_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото свідотцва про народження дитини'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='child_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День народження дитини'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='child_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПІБ дитини'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='copy_of_marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото копії свідотцтва про шлюб'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електрона пошта'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ваше ПІБ'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_passport',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото паспорта'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_residence_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото довідки про адресу'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_telefon_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_tin',
            field=models.IntegerField(blank=True, null=True, verbose_name='РНОКПП'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_tin_file',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото РНОКПП'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='foreigner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Іноземець'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дівоче прізвище'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Відгук'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПІБ чоловіка/дружини'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вулиця чоловіка/дружини'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_tin',
            field=models.IntegerField(blank=True, null=True, verbose_name='РНОКПП чоловіка/дружини'),
        ),
    ]
