# Generated by Django 4.1 on 2022-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0003_divorcement_child_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcement',
            name='parting_period',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cрок протягом якого не проживаємо разом'),
        ),
        migrations.AlterField(
            model_name='divorcement',
            name='first_person_telefon_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='divorcement',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Токен'),
        ),
    ]
