# Generated by Django 4.1 on 2022-08-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('divorcements', '0004_divorcement_parting_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts_cities', to='courts.city', verbose_name=''),
        ),
    ]
