# Generated by Django 4.1 on 2022-08-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('divorcements', '0005_divorcement_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorcement',
            name='city',
        ),
        migrations.AddField(
            model_name='divorcement',
            name='court_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_cities', to='courts.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_person_cities', to='courts.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_person_cities', to='courts.city', verbose_name='Місто'),
        ),
    ]
