# Generated by Django 4.1 on 2022-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0007_alter_divorcement_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divorcement',
            old_name='first_person_telefon_number',
            new_name='first_person_phone_number',
        ),
        migrations.AddField(
            model_name='divorcement',
            name='court_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва суду'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='first_person_zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='індекс'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='divorcement',
            name='second_person_zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='індекс'),
        ),
    ]
