# Generated by Django 4.1 on 2022-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0010_rename_birthday_divorcementchild_child_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorcement',
            name='child_birth_certificate',
        ),
        migrations.AddField(
            model_name='divorcement',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='divorcementchild',
            name='child_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Фото свідотцва про народження дитини'),
        ),
    ]
