# Generated by Django 4.1 on 2022-09-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0012_divorcement_child_birth_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorcement',
            name='child_birth_certificate',
        ),
    ]
