# Generated by Django 4.1 on 2022-09-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0013_remove_divorcement_child_birth_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorcement',
            name='copy_of_marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото копії свідотцтва про шлюб'),
        ),
        migrations.AlterField(
            model_name='divorcement',
            name='first_person_passport',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='divorcement',
            name='first_person_residence_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото довідки про адресу'),
        ),
        migrations.AlterField(
            model_name='divorcement',
            name='first_person_tin_file',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото РНОКПП'),
        ),
        migrations.AlterField(
            model_name='divorcementchild',
            name='child_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото свідотцва про народження дитини'),
        ),
    ]
