# Generated by Django 4.1 on 2022-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0014_alter_divorcement_copy_of_marriage_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorcement',
            name='copy_of_marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='divorcements/docs/', verbose_name='Фото копії свідотцтва про шлюб'),
        ),
    ]
