# Generated by Django 4.1 on 2022-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0015_alter_divorcement_copy_of_marriage_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorcement',
            name='copy_of_marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото копії свідотцтва про шлюб'),
        ),
    ]
