# Generated by Django 4.1 on 2022-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorcements', '0016_alter_divorcement_copy_of_marriage_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorcement',
            name='first_person_passport',
            field=models.FileField(blank=True, null=True, upload_to='media/images/', verbose_name='Фото паспорта'),
        ),
    ]
