# Generated by Django 4.1 on 2022-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_courtfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtfee',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Барський районний суд Вінницької області'),
        ),
    ]
