# Generated by Django 4.1 on 2022-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_courtfee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtfee',
            name='recipient_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рахунок отримувача'),
        ),
    ]
