# Generated by Django 4.1 on 2022-09-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_alter_courtfee_recipient_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Барський районний суд Вінницької області')),
                ('recipient_of_money', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отримувач коштів')),
                ('recipient_code_edrpou', models.IntegerField(blank=True, null=True, verbose_name='Код отримувача (код за ЄДРПОУ)')),
                ('recipient_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Банк отримувача')),
                ('recipient_code_mfo', models.IntegerField(blank=True, null=True, verbose_name='Код банку отримувача (МФО)')),
                ('recipient_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рахунок отримувача')),
                ('budget_code', models.IntegerField(blank=True, null=True, verbose_name='Код класифікації доходів бюджету')),
                ('purpose_of_payment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Призначення платежу')),
                ('link', models.CharField(default='', max_length=2083, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.city')),
            ],
            options={
                'verbose_name': 'Судовий збір',
                'verbose_name_plural': 'Судовий збір',
            },
        ),
        migrations.DeleteModel(
            name='CourtFee',
        ),
    ]
