# Generated by Django 4.0.6 on 2022-08-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
