# Generated by Django 4.1 on 2022-08-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_homepage'),
        ('content', '0007_initial'),
    ]

    operations = [
    ]
