# Generated by Django 4.1 on 2022-08-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_merge_0003_homepage_0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'домашня сторінка', 'verbose_name_plural': 'домашня сторінка'},
        ),
    ]
