# Generated by Django 4.1 on 2022-09-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_blog_id'),
        ('content', '0009_alter_homepage_options'),
    ]

    operations = [
    ]
