# Generated by Django 4.1 on 2022-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_merge_0003_alter_blog_id_0009_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
